import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        overlay: "rgb(var(--overlay) / <alpha-value>)",
        "card-translucent": "rgb(var(--card-translucent) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
        "success-strong": "rgb(var(--success-strong) / <alpha-value>)",
        "success-foreground": "rgb(var(--success-foreground) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        "danger-foreground": "rgb(var(--danger-foreground) / <alpha-value>)",
        "danger-soft": "rgb(var(--danger-soft) / <alpha-value>)",
        "danger-hover": "rgb(var(--danger-hover) / <alpha-value>)",
        "danger-border": "rgb(var(--danger-border) / <alpha-value>)",
        "surface-sunken": "rgb(var(--surface-sunken) / <alpha-value>)",
        "primary-hover": "rgb(var(--primary-hover) / <alpha-value>)",
        "primary-pressed": "rgb(var(--primary-pressed) / <alpha-value>)",
        "border-strong": "rgb(var(--border-strong) / <alpha-value>)",
        subtle: "rgb(var(--subtle) / <alpha-value>)",
        soft: "rgb(var(--soft) / <alpha-value>)",
        "neutral-strong": "rgb(var(--neutral-strong) / <alpha-value>)",
        "neutral-soft": "rgb(var(--neutral-soft) / <alpha-value>)",
        "muted-strong": "rgb(var(--muted-strong) / <alpha-value>)",
        "focus-muted": "rgb(var(--focus-muted) / <alpha-value>)",
        "placeholder-muted": "rgb(var(--placeholder-muted) / <alpha-value>)",
        bright: "rgb(var(--bright) / <alpha-value>)",
        shade: "rgb(var(--shade) / <alpha-value>)",
        "success-soft": "rgb(var(--success-soft) / <alpha-value>)",
        "success-text": "rgb(var(--success-text) / <alpha-value>)",
        "success-border": "rgb(var(--success-border) / <alpha-value>)",
        "warning-text": "rgb(var(--warning-text) / <alpha-value>)",
        "warning-border": "rgb(var(--warning-border) / <alpha-value>)",
      },
      boxShadow: {
        "card-inset": "inset 0 0 0 1px rgb(var(--overlay) / 0.12)",
        "card-lift": "0 12px 28px rgb(var(--shade) / 0.42)",
      },
      fontSize: {
        nano: "9px",
        micro: "10px",
        label: "11px",
        caption: "12px",
        subheading: "18px",
        heading: "22px",
      },
      letterSpacing: {
        "label-xs": "0.4px",
        label: "0.45px",
        "label-sm": "0.5px",
        "label-lg": "0.55px",
        caps: "0.6px",
      },
      lineHeight: {
        "body-sm": "14px",
        body: "15px",
        label: "16.5px",
        title: "19.5px",
      },
      spacing: {
        "inset-sm": "9px",
        inset: "13px",
        "inset-lg": "17px",
        control: "42px",
        "icon-lg": "45px",
        "row-md": "52px",
        "row-lg": "61px",
        "panel-min": "80px",
        "menu-offset": "130px",
        "auth-header": "133px",
        "sidebar-sm": "240px",
        sidebar: "256px",
        toast: "340px",
      },
      maxWidth: {
        popover: "320px",
        "auth-card": "448px",
        shell: "1200px",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};

export default config;
