UPDATE notes
SET embedding_pending = TRUE
WHERE embedding IS NOT NULL;

ALTER TABLE notes
ALTER COLUMN embedding TYPE VECTOR(1024)
USING CASE
  WHEN embedding IS NULL THEN NULL::VECTOR(1024)
  ELSE NULL::VECTOR(1024)
END;
